version: '3.8'

services:
  mongodb:
    image: mongo:latest  
    container_name: mongo-container
    ports:
      - "27017:27017" 
    environment:
      MONGO_INITDB_ROOT_USERNAME: root  # Usuário de root
      MONGO_INITDB_ROOT_PASSWORD: examplepassword  # Senha do root
    volumes:
      - mongodb-data:/data/db 
    networks:
      - app-network

volumes:
  mongodb-data:

networks:
  app-network:
    driver: bridge
